- src/main/java/com/play/hiclear/common/enums/Ranks.java
- src/main/java/com/play/hiclear/common/exception/ErrorCode.java
- src/main/java/com/play/hiclear/common/utils/JwtUtil.java
- src/main/java/com/play/hiclear/config/JPAConfig.java
- src/main/java/com/play/hiclear/config/JwtAuthenticationToken.java
- src/main/java/com/play/hiclear/config/JwtSecurityFilter.java
- src/main/java/com/play/hiclear/config/SecurityConfig.java
- src/main/java/com/play/hiclear/domain/auth/controller/AuthController.java
- src/main/java/com/play/hiclear/domain/auth/dto/request/LoginRequest.java
- src/main/java/com/play/hiclear/domain/auth/dto/request/SignupRequest.java
- src/main/java/com/play/hiclear/domain/auth/dto/response/LoginResponse.java
- src/main/java/com/play/hiclear/domain/auth/dto/response/SignupResponse.java
- src/main/java/com/play/hiclear/domain/auth/service/AuthService.java
- src/main/java/com/play/hiclear/domain/user/entity/User.java
- src/main/java/com/play/hiclear/domain/user/enums/UserRole.java
- src/main/java/com/play/hiclear/domain/user/repository/UserRepository.java
- SpringSecurity를 통한 인증/인가 구현
- 회원가입, 로그인 기능 구현
- Ranks enum 입력받을 때 검증 추가
> [FEAT] 회원가입 및 로그인 기능 구현

- src/main/java/com/play/hiclear/common/exception/CustomException.java
- src/main/java/com/play/hiclear/common/exception/ErrorCode.java
- src/main/java/com/play/hiclear/common/exception/GlobalExceptionHandler.java
- src/main/java/com/play/hiclear/domain/meeting/controller/MeetingController.java
- src/main/java/com/play/hiclear/domain/meeting/dto/request/CreateMeetingRequest.java
- src/main/java/com/play/hiclear/domain/meeting/dto/request/MeetingCreateEditRequest.java
- src/main/java/com/play/hiclear/domain/meeting/dto/response/MeetingSearchDetailResponse.java
- src/main/java/com/play/hiclear/domain/meeting/dto/response/MeetingSearchResponse.java
- src/main/java/com/play/hiclear/domain/meeting/entity/Meeting.java
- src/main/java/com/play/hiclear/domain/meeting/enums/SortType.java
- src/main/java/com/play/hiclear/domain/meeting/repository/MeetingRepository.java
- src/main/java/com/play/hiclear/domain/meeting/service/MeetingService.java
- src/main/java/com/play/hiclear/domain/participant/controller/ParticipantController.java
- src/main/java/com/play/hiclear/domain/participant/entity/Participant.java
- src/main/java/com/play/hiclear/domain/participant/repository/ParticipantRepository.java
- src/main/java/com/play/hiclear/domain/participant/service/ParticipantService.java
- 번개 생성, 수정, 삭제 구현
- Meeting 컨트롤러, 서비스, 리포 생성
- Participant 컨트롤러, 서비스, 리포 생성, 관련 enum생성
> [ADD] 번개 생성, 수정, 삭제

- src/main/java/com/play/hiclear/domain/auth/dto/request/AuthDeleteRequest.java
- src/main/java/com/play/hiclear/domain/auth/dto/request/AuthLoginRequest.java
- src/main/java/com/play/hiclear/domain/auth/dto/request/AuthSignupRequest.java
- src/main/java/com/play/hiclear/domain/court/dto/request/CourtCreateRequest.java
- src/main/java/com/play/hiclear/domain/gym/dto/request/GymCreateRequest.java
- src/main/java/com/play/hiclear/domain/gym/dto/request/GymUpdateRequest.java
- src/main/java/com/play/hiclear/domain/timeslot/dto/request/TimeSlotRequest.java
- src/main/java/com/play/hiclear/domain/timeslot/sevice/TimeSlotService.java
- src/main/java/com/play/hiclear/domain/user/controller/UserController.java
- src/main/java/com/play/hiclear/domain/user/service/UserService.java
- src/test/java/com/play/hiclear/domain/court/service/CourtServiceTest.java
- src/test/java/com/play/hiclear/domain/gym/service/GymServiceTest.java
- src/test/java/com/play/hiclear/domain/timeslot/sevice/TimeSlotServiceTest.java
- src/test/java/com/play/hiclear/domain/user/service/UserServiceTest.java
- User Service
- Gym Service
- Court Service
- TimeSlot Service
테스트 코드 작성 및 코드 리펙토링
> [TEST] Service 테스트 코드 작성

- build.gradle
- src/main/java/com/play/hiclear/domain/meeting/dto/request/MeetingCreateEditRequest.java
- src/main/java/com/play/hiclear/domain/meeting/entity/Meeting.java
- src/main/java/com/play/hiclear/domain/meeting/service/MeetingService.java
- src/main/java/com/play/hiclear/domain/participant/service/ParticipantService.java
- src/test/java/com/play/hiclear/domain/meeting/service/MeetingServiceTest.java
- src/test/java/com/play/hiclear/domain/participant/service/ParticipantServiceTest.java
변경 및 생성된 파일은 다음과 같습니다
[TEST]
- MeetingServiceTest.java
- ParticipantServiceTest.java
[ADD]
- MeetingController.java
- MeetingService.java
- Meeting.java
> [TEST][ADD] testcode 추가 및 Meeting 에 번개완료표기 기능 추가

- src/main/java/com/play/hiclear/common/exception/ErrorCode.java
- src/main/java/com/play/hiclear/common/message/SuccessMessage.java
- src/main/java/com/play/hiclear/domain/club/controller/ClubController.java
- src/main/java/com/play/hiclear/domain/club/dto/request/ClubCreateRequest.java
- src/main/java/com/play/hiclear/domain/club/dto/request/ClubDeleteRequest.java
- src/main/java/com/play/hiclear/domain/club/dto/request/ClubUpdateRequest.java
- src/main/java/com/play/hiclear/domain/club/entity/Club.java
- src/main/java/com/play/hiclear/domain/club/repository/ClubRepository.java
- src/main/java/com/play/hiclear/domain/club/service/ClubService.java
- src/main/java/com/play/hiclear/domain/clubmember/controller/ClubMemberController.java
- src/main/java/com/play/hiclear/domain/clubmember/dto/ClubMemberChangeRoleRequest.java
- src/main/java/com/play/hiclear/domain/clubmember/dto/request/ClubMemberChangeRoleRequest.java
- src/main/java/com/play/hiclear/domain/clubmember/dto/request/ClubMemberExpelRequest.java
- src/main/java/com/play/hiclear/domain/clubmember/entity/ClubMember.java
- src/main/java/com/play/hiclear/domain/clubmember/enums/ClubMemberRole.java
- src/main/java/com/play/hiclear/domain/clubmember/service/ClubMemberService.java
- src/main/java/com/play/hiclear/domain/comment/controller/CommentController.java
- src/main/java/com/play/hiclear/domain/comment/dto/request/CommentCreateRequest.java
- src/main/java/com/play/hiclear/domain/comment/dto/request/CommentDeleteRequest.java
- src/main/java/com/play/hiclear/domain/comment/dto/request/CommentUpdateRequest.java
- src/main/java/com/play/hiclear/domain/comment/entity/Comment.java
- src/main/java/com/play/hiclear/domain/comment/repository/CommentRepository.java
- src/main/java/com/play/hiclear/domain/comment/service/CommentService.java
- src/main/java/com/play/hiclear/domain/thread/controller/ThreadController.java
- src/main/java/com/play/hiclear/domain/thread/repository/ThreadRepository.java
- src/main/java/com/play/hiclear/domain/thread/service/ThreadService.java
- src/main/java/com/play/hiclear/domain/user/repository/UserRepository.java
- src/test/java/com/play/hiclear/domain/club/service/ClubServiceTest.java
- src/test/java/com/play/hiclear/domain/schedule/service/ScheduleServiceTest.java
1. 튜터님 코드리뷰사항 리팩토링
2. Contoller 성공 메세지 작성 및 적용
> 리팩토링 및 Success 메세지 작성 및 적용

- src/main/java/com/play/hiclear/common/exception/ErrorCode.java
- src/main/java/com/play/hiclear/common/message/SuccessMessage.java
- src/main/java/com/play/hiclear/domain/court/repository/CourtRepository.java
- src/main/java/com/play/hiclear/domain/gym/repository/GymRepository.java
- src/main/java/com/play/hiclear/domain/reservation/controller/ReservationController.java
- src/main/java/com/play/hiclear/domain/reservation/dto/request/ReservationChangeStatusRequest.java
- src/main/java/com/play/hiclear/domain/reservation/dto/request/ReservationRequest.java
- src/main/java/com/play/hiclear/domain/reservation/enums/ReservationStatus.java
- src/main/java/com/play/hiclear/domain/reservation/repository/ReservationQueryRepository.java
- src/main/java/com/play/hiclear/domain/reservation/repository/ReservationQueryRepositoryImpl.java
- src/main/java/com/play/hiclear/domain/reservation/repository/ReservationRepository.java
- src/main/java/com/play/hiclear/domain/reservation/service/ReservationService.java
- src/main/java/com/play/hiclear/domain/timeslot/repository/TimeSlotRepository.java
- src/test/java/com/play/hiclear/domain/reservation/controller/ReservationControllerTest.java
- src/test/java/com/play/hiclear/domain/reservation/service/ReservationServiceTest.java
1. 튜터님께서 말씀하신 코드 리뷰 리팩토링
2. 중복된 코드 분리
3. 코드 컨벤션 맞추기(authUser.getEmail() -> authUser)
4. 성공 메시지를 enum을 통해 사
> [FIX] 예약 코드 리팩토링

- src/main/java/com/play/hiclear/common/exception/ErrorCode.java
- src/main/java/com/play/hiclear/common/exception/GlobalExceptionHandler.java
- src/main/java/com/play/hiclear/common/message/SuccessMessage.java
- src/main/java/com/play/hiclear/domain/meeting/controller/MeetingController.java
- src/main/java/com/play/hiclear/domain/meeting/dto/request/MeetingCreateEditRequest.java
- src/main/java/com/play/hiclear/domain/meeting/entity/Meeting.java
- src/main/java/com/play/hiclear/domain/meeting/repository/MeetingQueryDslRepositoryImpl.java
- src/main/java/com/play/hiclear/domain/meeting/repository/MeetingRepository.java
- src/main/java/com/play/hiclear/domain/meeting/service/MeetingService.java
- src/main/java/com/play/hiclear/domain/participant/controller/ParticipantController.java
- src/main/java/com/play/hiclear/domain/participant/dto/ParticipantUpdateRequest.java
- src/main/java/com/play/hiclear/domain/participant/repository/ParticipantRepository.java
- src/main/java/com/play/hiclear/domain/participant/service/ParticipantService.java
- src/test/java/com/play/hiclear/domain/meeting/service/MeetingServiceTest.java
- src/test/java/com/play/hiclear/domain/participant/service/ParticipantServiceTest.java
- java docs 주석달기
- 성공 메시지 이넘으로 바꾸기
- QueryDSL에서 인원이 다 모인 번개는 다건 조회에서 감추기
- repository에서 findById 리펙토일
- 서비스단에서 반복되는 로직 리펙토링
> [REFACTOR] Meeting & Participant

- src/main/java/com/play/hiclear/domain/schedule/controller/ScheduleController.java
- src/main/java/com/play/hiclear/domain/schedule/dto/response/ScheduleSearchResponse.java
- src/main/java/com/play/hiclear/domain/schedule/repository/ScheduleQueryRepository.java
- src/main/java/com/play/hiclear/domain/schedule/repository/ScheduleQueryRepositoryImpl.java
- src/main/java/com/play/hiclear/domain/schedule/repository/ScheduleRepository.java
- src/main/java/com/play/hiclear/domain/schedule/service/ScheduleService.java
- src/test/java/com/play/hiclear/domain/schedule/service/ScheduleServiceTest.java
- 중복된 코드는 메서드로 빼서 사용
- 목록 조회를 할 때 Page를 사용해서 검색 기능 추가
- 코드 컨벤션 맞추기(authUser.getEmail() -> authUser)
> [FIX] 모임일정 코드 리팩토링

- src/main/java/com/play/hiclear/common/dto/response/GeoCodeAddress.java
- src/main/java/com/play/hiclear/common/dto/response/GeoCodeDocument.java
- src/main/java/com/play/hiclear/common/service/GeoCodeService.java
- src/main/resources/application.properties
- 장소를 입력하면 도로명 주소도 같이 API를 통해 조회
- 도로명 주소, 위도, 경도도 같이 가져온다.
> [FIX] GPS를 이용하여 주소 위치 가져오기(도로명, 위도, 경도)

- src/main/java/com/play/hiclear/common/exception/ErrorCode.java
- src/main/java/com/play/hiclear/domain/board/controller/BoardController.java
- src/main/java/com/play/hiclear/domain/board/repository/BoardRepository.java
- src/main/java/com/play/hiclear/domain/board/service/BoardService.java
- src/main/java/com/play/hiclear/domain/comment/entity/Comment.java
- src/main/java/com/play/hiclear/domain/likes/controller/LikesController.java
- src/main/java/com/play/hiclear/domain/likes/entity/Likes.java
- src/main/java/com/play/hiclear/domain/likes/repository/LikesRepository.java
- src/main/java/com/play/hiclear/domain/likes/service/LikesService.java
- src/main/java/com/play/hiclear/domain/meeting/repository/MeetingRepository.java
- src/main/java/com/play/hiclear/domain/participant/repository/ParticipantRepository.java
- src/main/java/com/play/hiclear/domain/review/controller/ReviewController.java
- src/main/java/com/play/hiclear/domain/review/dto/request/ReviewCreateRequest.java
- src/main/java/com/play/hiclear/domain/review/dto/response/ReviewCreateResponse.java
- src/main/java/com/play/hiclear/domain/review/entity/Review.java
- src/main/java/com/play/hiclear/domain/review/enums/MannerRank.java
- src/main/java/com/play/hiclear/domain/review/repository/ReviewRepository.java
- src/main/java/com/play/hiclear/domain/review/service/ReviewService.java
> feat: [update][fix][refactor][add]유저리뷰, 코드리펙토링

- src/main/java/com/play/hiclear/domain/board/service/BoardService.java
- src/main/java/com/play/hiclear/domain/likes/service/LikesService.java
- src/main/java/com/play/hiclear/domain/review/repository/ReviewRepository.java
- src/main/java/com/play/hiclear/domain/review/service/ReviewService.java
> feat: [fix]메서드 수정

- src/main/java/com/play/hiclear/common/exception/ErrorCode.java
- src/main/java/com/play/hiclear/domain/reservation/controller/ReservationController.java
- src/main/java/com/play/hiclear/domain/reservation/entity/Reservation.java
- src/main/java/com/play/hiclear/domain/reservation/service/ReservationService.java
- src/main/java/com/play/hiclear/domain/schedule/controller/ScheduleController.java
- src/main/java/com/play/hiclear/domain/schedule/dto/request/ScheduleRequest.java
- src/main/java/com/play/hiclear/domain/schedule/dto/request/ScheduleUpdateRequest.java
- src/main/java/com/play/hiclear/domain/schedule/dto/response/ScheduleSearchDetailResponse.java
- src/main/java/com/play/hiclear/domain/schedule/dto/response/ScheduleSearchResponse.java
- src/main/java/com/play/hiclear/domain/schedule/entity/Schedule.java
- src/main/java/com/play/hiclear/domain/schedule/repository/ScheduleRepository.java
- src/main/java/com/play/hiclear/domain/schedule/service/ScheduleService.java
- GeoCoding 적용
- 시간 관련 메서드도 추가
- 예약할 때 사립 체육관은 불가능
- @AllArgsConstructor 제외
> [FIX] 예약 & 모임일정 코드 리팩토링

- src/main/java/com/play/hiclear/domain/board/repository/BoardRepository.java
- src/main/java/com/play/hiclear/domain/board/service/BoardService.java
- src/main/java/com/play/hiclear/domain/comment/service/CommentService.java
- src/main/java/com/play/hiclear/domain/likes/controller/LikesController.java
- src/main/java/com/play/hiclear/domain/likes/service/LikesService.java
- src/main/java/com/play/hiclear/domain/review/controller/ReviewController.java
- src/main/java/com/play/hiclear/domain/review/dto/response/ReviewSearchResponse.java
- src/main/java/com/play/hiclear/domain/review/service/ReviewService.java
> feat: [add][update][refactor]유저리뷰 수정, 리펙토링

- build.gradle
- src/main/java/com/play/hiclear/common/exception/ErrorCode.java
- src/main/java/com/play/hiclear/domain/meeting/controller/MeetingController.java
- src/main/java/com/play/hiclear/domain/meeting/dto/request/MeetingCreateRequest.java
- src/main/java/com/play/hiclear/domain/meeting/dto/request/MeetingEditRequest.java
- src/main/java/com/play/hiclear/domain/meeting/entity/Meeting.java
- src/main/java/com/play/hiclear/domain/meeting/repository/MeetingQueryDslRepositoryImpl.java
- src/main/java/com/play/hiclear/domain/meeting/service/MeetingService.java
- src/main/java/com/play/hiclear/domain/participant/service/ParticipantService.java
- src/test/java/com/play/hiclear/domain/meeting/service/MeetingServiceTest.java
- src/test/java/com/play/hiclear/domain/participant/service/ParticipantServiceTest.java
- 미팅수정시 null값처리
- 미팅이 다 차면 더 수락도 안되고
- 미팅이 다 차면 신청도 안되도록
- 미팅수정 및 삭제 권한에러 메시지
- 미팅 삭제된거 조회 않게
- 신청서 수정에서 meeting Id와 participant 아이디가 맞는지 수정
> [REFACTOR]

- src/main/java/com/play/hiclear/common/exception/ErrorCode.java
- src/main/java/com/play/hiclear/common/message/SuccessMessage.java
- src/main/java/com/play/hiclear/domain/reservation/service/ReservationService.java
- src/main/java/com/play/hiclear/domain/schduleparticipant/repository/ScheduleParticipantRepository.java
- src/main/java/com/play/hiclear/domain/schedule/controller/ScheduleController.java
- src/main/java/com/play/hiclear/domain/schedule/dto/request/ScheduleUpdateRequest.java
- src/main/java/com/play/hiclear/domain/schedule/service/ScheduleService.java
- src/test/java/com/play/hiclear/domain/reservation/controller/ReservationControllerTest.java
- src/test/java/com/play/hiclear/domain/reservation/service/ReservationServiceTest.java
- src/test/java/com/play/hiclear/domain/schedule/service/ScheduleServiceTest.java
- 모임일정 참가자 추가 기능 구현
- 모임일정 참가자 삭제 기능 구현
- 테스트 코드 수정
> [FIX] 예약 & 모임일정 코드 리팩토링 및 테스트 코드 수정

- src/main/java/com/play/hiclear/domain/board/controller/BoardController.java
- src/main/java/com/play/hiclear/domain/board/dto/request/BoardCreateRequest.java
- src/main/java/com/play/hiclear/domain/board/dto/request/BoardUpdateRequest.java
- src/main/java/com/play/hiclear/domain/board/repository/BoardRepository.java
- src/main/java/com/play/hiclear/domain/participant/repository/ParticipantRepository.java
- src/main/java/com/play/hiclear/domain/review/dto/response/ReviewSearchResponse.java
- src/main/java/com/play/hiclear/domain/review/entity/Review.java
- src/main/java/com/play/hiclear/domain/review/repository/ReviewRepository.java
- src/main/java/com/play/hiclear/domain/review/service/ReviewService.java
리뷰가능한 유저를 불러올떄 이미 리뷰를 작성한 건에 대해서는 리뷰 작성이 불가능하도록 막음. Repository쪽의 코드 병합.
보드 생성, 수정 null시 오류 메세지 추가
> feat: [update][fix]중복리뷰막음, 코드 병합

- src/main/java/com/play/hiclear/common/exception/ErrorCode.java
- src/main/java/com/play/hiclear/common/utils/DistanceCalculator.java
- src/main/java/com/play/hiclear/domain/gym/controller/GymController.java
- src/main/java/com/play/hiclear/domain/gym/service/GymService.java
- src/main/java/com/play/hiclear/domain/meeting/controller/MeetingController.java
- src/main/java/com/play/hiclear/domain/meeting/dto/request/MeetingCreateRequest.java
- src/main/java/com/play/hiclear/domain/meeting/dto/response/MeetingSearchResponse.java
- src/main/java/com/play/hiclear/domain/meeting/enums/SortType.java
- src/main/java/com/play/hiclear/domain/meeting/repository/MeetingQueryDslRepository.java
- src/main/java/com/play/hiclear/domain/meeting/repository/MeetingQueryDslRepositoryImpl.java
- src/main/java/com/play/hiclear/domain/meeting/service/MeetingService.java
- src/main/java/com/play/hiclear/domain/participant/service/ParticipantService.java
- src/main/java/com/play/hiclear/domain/schedule/dto/response/ClubScheduleResponse.java
- src/main/java/com/play/hiclear/domain/schedule/repository/ScheduleRepository.java
[ADD] 체육관 검색시 자주열리는 모임들 이름과 당날 모임일정 불러오기
> [ADD] 체육관 검색시 자주열리는 모임들 이름과 당날 모임일정 불러오기

- src/main/java/com/play/hiclear/domain/gym/controller/GymController.java
- src/main/java/com/play/hiclear/domain/gym/service/GymDummyService.java
- src/main/java/com/play/hiclear/domain/gym/service/GymService.java
- src/main/java/com/play/hiclear/domain/schedule/repository/ScheduleRepository.java
변경된 파일:
- schedule repository 
- gym controller & service
> [FIX]  schedule repository 쿼리 문법 수정

- src/main/resources/application.properties
- src/test/java/com/play/hiclear/HiClearApplicationTests.java
- src/test/java/com/play/hiclear/domain/auth/service/AuthServiceTest.java
- src/test/java/com/play/hiclear/domain/board/service/BoardServiceTest.java
- src/test/java/com/play/hiclear/domain/club/service/ClubServiceTest.java
- src/test/java/com/play/hiclear/domain/comment/service/CommentServiceTest.java
- src/test/java/com/play/hiclear/domain/court/service/CourtServiceTest.java
- src/test/java/com/play/hiclear/domain/gym/service/GymServiceTest.java
- src/test/java/com/play/hiclear/domain/likes/service/LikesServiceTest.java
- src/test/java/com/play/hiclear/domain/meeting/service/MeetingServiceTest.java
- src/test/java/com/play/hiclear/domain/participant/service/ParticipantServiceTest.java
- src/test/java/com/play/hiclear/domain/reservation/controller/ReservationControllerTest.java
- src/test/java/com/play/hiclear/domain/reservation/service/ReservationServiceTest.java
- src/test/java/com/play/hiclear/domain/schedule/service/ScheduleServiceTest.java
- src/test/java/com/play/hiclear/domain/thread/service/ThreadServiceTest.java
- src/test/java/com/play/hiclear/domain/timeslot/sevice/TimeSlotServiceTest.java
- src/test/java/com/play/hiclear/domain/user/service/UserServiceTest.java
-  AWS RDS와 연결 설정
- Data Source 연결 필요
- Test 코드 주석 처리
> [FIX] application.properties 수정

- src/main/java/com/play/hiclear/common/enums/Ranks.java
- src/main/java/com/play/hiclear/common/exception/ErrorCode.java
- src/main/java/com/play/hiclear/domain/participant/repository/ParticipantRepository.java
- src/main/java/com/play/hiclear/domain/review/controller/ReviewController.java
- src/main/java/com/play/hiclear/domain/review/dto/response/UserStatisticsResponse.java
- src/main/java/com/play/hiclear/domain/review/enums/MannerRank.java
- src/main/java/com/play/hiclear/domain/review/service/ReviewService.java
리뷰서비스 반환값 숫자 -> enum값으로 변경
중복리뷰 처리 코드 추가
리뷰생성에 분산락 적용
> feat: [add][update][fix][refactor] 분산락 적용

- build.gradle
- src/main/java/com/play/hiclear/HiClearApplication.java
- src/main/java/com/play/hiclear/common/batch/Scheduler/BatchScheduler.java
- src/main/java/com/play/hiclear/common/batch/Tasklet/ReservationsTasklet.java
- src/main/java/com/play/hiclear/common/batch/Tasklet/ScheduleTask.java
- src/main/java/com/play/hiclear/common/exception/ErrorCode.java
- src/main/java/com/play/hiclear/config/BatchConfig.java
- src/main/java/com/play/hiclear/domain/reservation/controller/ReservationController.java
- src/main/java/com/play/hiclear/domain/reservation/dto/request/ReservationRequest.java
- src/main/java/com/play/hiclear/domain/reservation/repository/ReservationQueryRepositoryImpl.java
- src/main/java/com/play/hiclear/domain/reservation/repository/ReservationRepository.java
- src/main/java/com/play/hiclear/domain/reservation/service/ReservationService.java
- src/main/java/com/play/hiclear/domain/schduleparticipant/repository/ScheduleParticipantRepository.java
- src/main/java/com/play/hiclear/domain/schedule/dto/response/ClubScheduleResponse.java
- src/main/java/com/play/hiclear/domain/schedule/entity/Schedule.java
- src/main/java/com/play/hiclear/domain/schedule/repository/ScheduleRepository.java
- src/main/java/com/play/hiclear/domain/schedule/service/ScheduleService.java
- src/main/resources/application.properties
- src/main/resources/schema.sql
- src/test/java/com/play/hiclear/domain/reservation/controller/ReservationControllerTest.java
- src/test/java/com/play/hiclear/domain/reservation/service/ReservationServiceTest.java
- src/test/java/com/play/hiclear/domain/schedule/service/ScheduleServiceTest.java
-  Spring Batch를 사용하여 지난 데이터 삭제
- 모임 일정, 예약 코드 수정
> [FIX] 예약, 모임일정 코드 수정 및 배치 작업 추가

- src/main/java/com/play/hiclear/domain/review/controller/ReviewController.java
- src/main/java/com/play/hiclear/domain/review/dto/request/ReviewCreateRequest.java
- src/main/java/com/play/hiclear/domain/review/dto/response/UserStatisticsResponse.java
- src/main/java/com/play/hiclear/domain/review/service/ReviewDummyService.java
- src/main/java/com/play/hiclear/domain/review/service/ReviewService.java
리뷰 조회, 생성 과정에 캐싱로직을 추가
리뷰더미데이터 10000개를 생성할 수 있는 API 추가
> feat: [add][fix][refactor]리뷰조회와 생성에 캐싱과정 추가

- src/main/java/com/play/hiclear/domain/meeting/service/MeetingService.java
- src/test/java/com/play/hiclear/domain/meeting/service/MeetingServiceTest.java
> [FIX] MeetingServiceTest 오류해결

- src/test/java/com/play/hiclear/domain/likes/service/LikesServiceTest.java
> feat: [fix]급히 수정
